version: '3'
networks:
  net1:
    external: true
    name: 'net1'
  net2:
    external: true
    name: 'net2'
  net3:
    external: true
    name: 'net3'

services:
  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      - MONGO_PASS=secret
      - MONGO_HOST=mongodb
      - MONGODB_URI=mongodb://admin:secret@mongodb:27017
      - ENABLE_WRITING_HANDLERS=false
      - REDIS_URI=redis://redis:6379
    networks:
      - net1
      - net2
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: mongodb
    image: mongo:8.0-rc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - net2
      - net3

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0-20-alpine3.19
    restart: always # fixes MongoNetworkError caused by mongodb not being ready when mongo-express starts.
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - net3
    depends_on:
      - mongodb

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"  
    networks:
      - net1
